#アプリケーションBeanプロパティ
property:
  session:
    userInfoKey: LOGIN_USER_SESSION
    idKey: CONNECT_SESSION_ID
    lockTime: 60 #分で指定
    contextName: /jsym-home
    

#mybatis設定 警告は問題無し
mybatis:
  configuration:
    jdbcTypeForNull: 'NULL'
    defaultStatementTimeout: 30
    mapUnderscoreToCamelCase: true
  type-aliases-package: jp.co.jdsnet.common.domain.entity

#サーバー設定
server:
  servlet:
    session:
      timeout: 3600 #秒指定 
      cookie:
        max-age: 3600 #秒指定

#spring設定
spring:
  datasource:
    driver-class-name: com.ibm.db2.jcc.DB2Driver
    hikari:
      connection-timeout: 20000
      auto-commit: false
      maximum-pool-size: 30
      minimum-idle: 0
      max-lifetime: 0
  main:
    banner-mode: off
    log-startup-info: false
    allow-bean-definition-overriding: true
  messages:
    basename: i18n/messages,i18n/ValidationMessages,i18n/itemlabel,i18n/titlelabel
    encoding: UTF-8
    cache-duration: 12h
    fallback-to-system-locale: false
  web:
    resources:
      cache:
        period: 365d
        use-last-modified: false
      chain:
        enabled: true
        strategy:
          content:
            enabled: true
            paths: /css/**,/js/**

#ログ設定
logging:
  config: classpath:config/logback-spring.xml
  group:
    db: 
      - jp.co.jdsnet.common.domain.mapper
      - com.zaxxer.hikari
    tomcat:
      - org.apache.catalina
      - org.apache.coyote
      - org.apache.tomcat
      - org.springframework.boot.web.embedded.tomcat
  level:
    root: info
    tomcat: warn
  charset:
    file: cp943
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p %-40.40logger{39} : %msg%n"
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
  operationlog:
    pattern: "%d{yyyy-MM-dd HH:mm:ss} %p %m %n"

#トランザクショントークン設定
keel:
  transaction:
    token:
      exclude-path-patterns:
      - /resources/**
      - /error/**/*.html