spring:
  profiles:
    active: dev
    group:
      common:
        - base
      dev:
        - common
        - dev
        - dev-backlendcost
      test:
        - common
        - test
      prod:
        - common
        - prod

#サーバー設定
server:
  servlet:
    context-path: /backlendcost
